//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.ClassRoom = new HashSet<ClassRoom>();
            this.GradeFee = new HashSet<GradeFee>();
            this.Subject = new HashSet<Subject>();
            this.Student = new HashSet<Student>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ClassficationID { get; set; }
    
        public virtual Classfication Classfication { get; set; }
        public virtual ICollection<ClassRoom> ClassRoom { get; set; }
        public virtual ICollection<GradeFee> GradeFee { get; set; }
        public virtual ICollection<Subject> Subject { get; set; }
        public virtual ICollection<Student> Student { get; set; }
    }
}
