//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeFee
    {
        public int GradeId { get; set; }
        public int FeeId { get; set; }
        public int Year { get; set; }
    
        public virtual Fee Fee { get; set; }
        public virtual Grade Grade { get; set; }
    }
}
