//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int FeeId { get; set; }
        public System.Guid StudentId { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public System.Guid EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Fee Fee { get; set; }
        public virtual Student Student { get; set; }
    }
}
