//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Day { get; set; }
        public int ClassRoomId { get; set; }
        public int SubjectId { get; set; }
        public int PeriodId { get; set; }
        public Nullable<int> TeacherId { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual Period Period { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
