//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Exam = new HashSet<Exam>();
            this.Schedule = new HashSet<Schedule>();
            this.Teacher = new HashSet<Teacher>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int GradeId { get; set; }
    
        public virtual ICollection<Exam> Exam { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<Teacher> Teacher { get; set; }
    }
}
